[project]
name = "dnamic-andor-artiq"
version = "0.1.0"
description = "ARTIQ integration (mediator/local device) for Andor camera"
requires-python = ">=3.10"
dependencies = ["artiq"]

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
